# Generated by Django 4.0.3 on 2022-04-17 07:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('typeContenu', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('contenu', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_post', models.DateField(auto_now_add=True)),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
