# Generated by Django 4.0.3 on 2022-04-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
