# Generated by Django 4.0.3 on 2022-04-22 01:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('profile', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
