# Generated by Django 4.0.3 on 2022-04-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_image_post_creator_image_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='image_creator',
        ),
    ]
