# Generated by Django 4.0.3 on 2022-04-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_creator_image_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='creator',
        ),
    ]
