# Generated by Django 4.0.4 on 2022-05-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=models.CharField(max_length=1024),
        ),
    ]
