# Generated by Django 4.0.4 on 2022-05-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('skill', models.CharField(default='Cyber Security', max_length=200)),
                ('profile', models.CharField(max_length=1024)),
                ('image_creator', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_join', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
