# Generated by Django 4.0.4 on 2022-05-01 14:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_creator_profile_alter_post_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='profile',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
