# Generated by Django 4.0.4 on 2022-05-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_creator_profile_alter_post_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_detail',
        ),
    ]
