# Generated by Django 4.0.4 on 2022-05-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_creator_post_author_rename_contenu_post_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='typeContenu',
        ),
    ]
