# Generated by Django 4.0.4 on 2022-05-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_body_post_contenu_rename_author_post_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
