# Generated by Django 4.0.4 on 2022-05-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_comment_author_remove_comment_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='add you commant her !'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
