# Generated by Django 4.0.4 on 2022-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_recommandation', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_recommandation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
