# Generated by Django 4.0.4 on 2022-05-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_recommandation_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandation',
            name='post',
        ),
    ]
