# Generated by Django 4.0.4 on 2022-05-07 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0026_remove_recommandation_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to=settings.AUTH_USER_MODEL),
        ),
    ]
