# Generated by Django 4.0.4 on 2022-05-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_recommandation_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommandation',
            old_name='post',
            new_name='user',
        ),
    ]
