# Generated by Django 4.0.4 on 2022-05-08 18:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_rename_post_recommandation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommandation',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
