# Generated by Django 4.0.4 on 2022-05-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_recommandation_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation',
            name='link',
            field=models.CharField(default='link', max_length=200),
        ),
    ]
