# Generated by Django 4.0.4 on 2022-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.TextField(default='answer'),
        ),
    ]
