# Generated by Django 4.0.4 on 2022-05-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_comment_answer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='response',
        ),
    ]
