# Generated by Django 4.0.4 on 2022-05-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_answer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comment',
        ),
    ]
