# Generated by Django 4.0.4 on 2022-05-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_delete_answer_comment_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=100)),
                ('date_comment_final', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField()),
            ],
        ),
    ]
