# Generated by Django 4.0.4 on 2022-05-13 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_commentfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfinal',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments+', to='blog.post'),
        ),
    ]
