# Generated by Django 4.0.4 on 2022-05-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_comment_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
            ],
        ),
        migrations.DeleteModel(
            name='CommentFinal',
        ),
    ]
