# Generated by Django 4.0.4 on 2022-05-13 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0043_test_delete_commentfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommandation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommandations', to=settings.AUTH_USER_MODEL),
        ),
    ]
