# Generated by Django 4.0.4 on 2022-05-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_alter_recommandation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandation',
            name='user',
        ),
    ]
